# Generated by Django 5.0.4 on 2024-04-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=30)),
                ('dog_age', models.CharField(max_length=2)),
                ('dog_breed', models.CharField(max_length=50)),
                ('dog_medical_notes', models.CharField(max_length=500)),
                ('dog_behavioral_notes', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=60)),
                ('owner_email', models.CharField(max_length=50)),
                ('owner_number', models.CharField(max_length=10)),
                ('owner_address', models.CharField(max_length=100)),
                ('owner_emergency_name', models.CharField(max_length=60)),
                ('owner_emergency_relation', models.CharField(max_length=30)),
                ('owner_emergency_number', models.CharField(max_length=10)),
            ],
        ),
    ]
