# Generated by Django 5.0.4 on 2024-04-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='owner_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
